version: "3.7"
services:
  app:
    build: .
    volumes:
      - './app:/go/app'
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
